version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - MONGODB_STATUS_HOST=mymongo
    ports:
      - 9011:9011
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: aegro-test