server:
  port: ${SERVER_PORT:9011}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017/aegro-test?authSource=admin
      authentication-database: admin
      database: aegro-test
  profiles:
    active: ${ACTIVE_PROFILE:dev}